image: ruby:2.6.3

cache:
  paths:
  - .vendor

before_script:
  - gem install bundler
  - bundle install --path .vendor

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
    expire_in: 366000 days
  only:
  - master
