# Site settings
title: "bogdanvlviv (Bogdan)"
email: "bogdanvlviv@gmail.com"
description: "#ruby developer. love #linux, #tmux and #vim."
baseurl: ""
url: "https://bogdanvlviv.github.io"
share_image: "/images/share-image.jpg"
twitter_username: "bogdanvlviv"
github_username: "bogdanvlviv"
gitlab_username: "bogdanvlviv"
disqus_username: "bogdanvlviv"
clicky_site_id: 100995792
google_analytics_id: "UA-89178612-1"
facebook_app_id: "644125232436147"
date_format: "%B %-d, %Y"
lang: "en"

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
