# Site settings
title: "bogdanvlviv (Bogdan)"
email: bogdanvlviv@gmail.com
description: "#ruby developer. love #linux, #tmux and #vim."
baseurl: ""
url: "https://bogdanvlviv.github.io"
twitter_username: bogdanvlviv
github_username: bogdanvlviv

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
