# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bogdanvlviv (Bogdan)
email: bogdanvlviv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  #ruby developer. love #linux, #tmux and #vim.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bogdanvlviv.github.io" # the base hostname & protocol for your site
twitter_username: bogdanvlviv
github_username:  bogdanvlviv

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
