# Site settings
title: "bogdanvlviv / Bogdan"
email: "bogdanvlviv@gmail.com"
description: "#rails contributor. #ruby consulting."
baseurl: ""
url: "https://bogdanvlviv.com"
image: "/images/main.jpg"
username: "bogdanvlviv"
twitter_username: "bogdanvlviv"
github_username: "bogdanvlviv"
disqus_username: "bogdanvlviv"
google_analytics_id: "UA-89178612-1"
google_maps_key: "AIzaSyALU_NaFdHwud0rA0paeA2_KAq0FRFoemc"
mailchimp_signup_form_url: "https://github.us10.list-manage.com/subscribe?u=68b0b78bb20c7de3f023a4888&id=b5d24413d3"
date_format: "%B %-d, %Y"
lang: "en"

# Build settings
markdown: kramdown
collections:
  posts:
    permalink: /:categories/:title.html
exclude:
  - CNAME
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
