# Site settings
title: "bogdanvlviv (Bogdan)"
email: "bogdanvlviv@gmail.com"
description: "#rails contributors team member. love #ruby, #linux, #tmux and #vim."
baseurl: ""
url: "https://bogdanvlviv.github.io"
share_image: "/images/share-image.jpg"
username: "bogdanvlviv"
twitter_username: "bogdanvlviv"
github_username: "bogdanvlviv"
gitlab_username: "bogdanvlviv"
disqus_username: "bogdanvlviv"
google_analytics_id: "UA-89178612-1"
facebook_app_id: "644125232436147"
mailchimp_signup_form_url: "https://github.us10.list-manage.com/subscribe?u=68b0b78bb20c7de3f023a4888&id=b5d24413d3"
date_format: "%B %-d, %Y"
lang: "en"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
