# Site settings
title: "bogdanvlviv (Bogdan)"
email: bogdanvlviv@gmail.com
description: "#ruby developer. love #linux, #tmux and #vim."
baseurl: ""
url: "https://bogdanvlviv.github.io"
twitter_username: bogdanvlviv
github_username: bogdanvlviv
gitlab_username: bogdanvlviv
disqus_username: bogdanvlviv
clicky_site_id: 100995792
google_analytics_id: "UA-89178612-1"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
