version: '3.7'

x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      RUBY_VERSION: '2.6.4'
      BUNDLER_VERSION: '2.0.2'
  image: bogdanvlviv_com:1.0.0
  stdin_open: true
  tty: true
  volumes:
   - .:/app:cached
   - bundle:/bundle
   - jekyll_cache:/app/.jekyll-cache
   - sass_cache:/app/.sass-cache
  tmpfs:
    - /tmp

services:
  runner:
    <<: *app
    command: /bin/bash
  jekyll:
    <<: *app
    command: 'bundle exec jekyll serve --drafts --host 0.0.0.0'
    ports:
      - '4000:4000'

volumes:
  bundle:
  jekyll_cache:
  sass_cache:
